Task #168716 feat: Capture field to capture and upload image on the s…
techjoomla/com_tjfields pull request #321
Opened 2021-02-19 03:57 UTC by ankush-maherwal

…erver

2021-02-19 05:48 UTC, manojLondhe requested changes

2021-02-19 05:48 UTC, manojLondhe commented on administrator/assets/js/captureimage.js
> +	jQuery.each(jQuery("#item-form").find(jQuery("input[onClick^='set_camera(']")), function (key, value) {
is this UCM specific?

2021-02-19 05:48 UTC, manojLondhe commented on administrator/assets/js/captureimage.js
> +		jQuery.each(jQuery(row).find(jQuery("input[id^='"+likeName+"']")), function (key, value) {
add enough comments pls

2021-02-19 05:48 UTC, manojLondhe commented on administrator/assets/js/captureimage.js
> +			if (jQuery('#'+jQuery(value).attr('id').replace('take_another', '_hasvalue')).val() == '0')
format entire file using some tool

2021-02-19 05:48 UTC, manojLondhe commented on administrator/models/fields/captureimage.php
> + * @package     Joomla.Platform
fix copyright section

2021-02-19 05:48 UTC, manojLondhe commented on administrator/models/fields/captureimage.php
> + * @package     Joomla.Platform
add ours too in addition to existing

2021-02-19 05:48 UTC, manojLondhe commented on administrator/models/fields/captureimage.php
> +		$doc->addScript(JUri::root() . 'media/com_tjfields/vendors/webcamjs/webcam.min.js');
add using HTMLHelper

2021-02-19 05:48 UTC, manojLondhe commented on site/helpers/tjfields.php
> +				$mediaPath = ($uploadPath != '') ? $uploadPath : JPATH_SITE . '/' . $fieldTable->type . 's/tjmedia/' . str_replace(".", "/", $client . "/");
`s/ ` is this correct?

2021-02-19 05:48 UTC, manojLondhe commented on site/helpers/tjfields.php
> +				file_put_contents($file, $imageBase64);
shouldn't we upload using code from TJMediaStorageLocal ?

2021-02-19 10:52 UTC, ankush-maherwal commented on administrator/assets/js/captureimage.js
> +	jQuery.each(jQuery("#item-form").find(jQuery("input[onClick^='set_camera(']")), function (key, value) {
no, its field-specific

2021-02-19 10:56 UTC, ankush-maherwal commented on administrator/assets/js/captureimage.js
> +			if (jQuery('#'+jQuery(value).attr('id').replace('take_another', '_hasvalue')).val() == '0')
done

2021-02-19 10:57 UTC, ankush-maherwal commented on site/helpers/tjfields.php
> +				$mediaPath = ($uploadPath != '') ? $uploadPath : JPATH_SITE . '/' . $fieldTable->type . 's/tjmedia/' . str_replace(".", "/", $client . "/");
yes, this will add all files of type image in a folder named images and video in a folder named videos. It's for plural of the field  type

2021-02-19 10:58 UTC, ankush-maherwal commented on site/helpers/tjfields.php
> +				file_put_contents($file, $imageBase64);
we do not upload file as the captured image is not a file but a stream of data. We pass the data and store it as image

2021-02-19 11:08 UTC, ankush-maherwal commented on administrator/models/fields/captureimage.php
> +		$doc->addScript(JUri::root() . 'media/com_tjfields/vendors/webcamjs/webcam.min.js');
done

2021-02-19 11:08 UTC, ankush-maherwal commented on administrator/models/fields/captureimage.php
> + * @package     Joomla.Platform
done

2021-02-19 11:17 UTC, ankush-maherwal commented on administrator/assets/js/captureimage.js
> +		jQuery.each(jQuery(row).find(jQuery("input[id^='"+likeName+"']")), function (key, value) {
done

2021-02-19 11:20 UTC, ankush-maherwal commented on administrator/assets/js/captureimage.js
> +var userAgentIsMobile = false;
we will do this in separate MR as we need this MR for reference to add code in DPE.

Issue #168893 created in the tracker for this.

2021-02-19 13:45 UTC, manojLondhe commented on administrator/assets/js/captureimage.js
> +	jQuery.each(jQuery("#item-form").find(jQuery("input[onClick^='set_camera(']")), function (key, value) {
im talking about `#item-form `

2021-02-22 05:34 UTC, ankush-maherwal commented on administrator/assets/js/captureimage.js
> +	jQuery.each(jQuery("#item-form").find(jQuery("input[onClick^='set_camera(']")), function (key, value) {
changed this as required

2021-02-22 07:03 UTC, merged